### PR TITLE
add Placeholder

### PR DESCRIPTION
**Pull request by hjiayz**
Placeholder

### CODE REVIEW

**Comment by dpc** [comment]
`__`? What's that?

**Comment by hjiayz** [comment]
use default::__;
fn foo(s:String){}

**Comment by hjiayz** [comment]
```
use default::default as __;
fn foo(s:String) {
    println!("{}",s);
}
foo(__());
```
```
use default::__;
fn foo(s:String) {
    println!("{}",s);
}
foo(__());
```

**Comment by dpc** [comment]
But... why? :D

**Review by BenjaminBrienen — CHANGES_REQUESTED** [review]
This doesn't make sense

**Pull request closed without merging**
